<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/title.png' width=500/><center>

<center>- Numpy의 모든 것을 배우지 않습니다. 데이터 전처리에 대한 부분만 학습 대상이 됩니다 -</center>

# 학습 목표

- 불리안 방식과 정수 방식의 인덱싱을 이해합니다.
- 인덱싱과 슬라이싱으로 원하는 데이터를 조회할 수 있습니다.


# 2. 배열 인덱싱과 슬라이싱

- 기본 자료형(리스트, 튜플 등) 보다 배열 인덱싱과 슬라이싱이 조금 어렵습니다.
- 배열은 선형대수를 위해 많이 사용되므로 어려운 부분은 우선 생략하고 넘어가도 될 것입니다.

In [2]:
# 라이브러리 불러오기
import numpy as np

**[기억할 것] 큰 차원을 따라갑니다**
- 0차원과 0차원이 만나면 0차원
- 0차원과 1차원이 만나면 1차원
- 1차원과 1차원이 만나면 1차원
- 2차원과 1차원이 만나면 2차원
- 2차원과 2차원이 만나면 2차원
- 0차원과 2차원이 만나면 1차원
- 범위는 현재 배열의 차원

## 2.1. 기본 인덱싱

**1) 1차원 배열**

- 1차원 배열은 리스트와 같은 방법으로 인덱싱합니다.
- 인덱스가 0부터 시작함을 꼭 기억하시기 바랍니다.

In [3]:
# 1차원 배열 만들기
a = np.array([1, 2, 3, 4, 5])
print(a)             

[1 2 3 4 5]


In [4]:
# 첫 번째 요소 확인
print(a[0])

1


In [5]:
# 네 번째 요소 확인
print(a[3])

4


In [6]:
# 마지막 요소 확인
print(a[-1])

5


In [7]:
# len 함수로 마지막 요소 확인
print(a[len(a) - 1])

5


**2) 2차원 배열**

- **배열[행,열]** 형태로 지정해 그 위치의 요소를 조회합니다.
- a[1, 1]는 a 배열의 두 번째 행, 두 번째 열에 있는 요소를 조회합니다.
- 인덱스는 0부터 시작함을 잊지 마세요.

In [8]:
# 3 x 3 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]])
print(a)             

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# 0행 0열 조회
print(a[0, 0])
print(a[0][0])

1
1


In [11]:
# 1행 2열 조회
print(a[1, 2])

6


In [12]:
# 마지막 행, 마지막 열 조회
print(a[-1, -1])

9


**특정 행 조회**

- **배열[[행번호], :]** 형태로 특정 행을 조회합니다.
- 모든 열을 선택하는 경우는 열에 대한 선택 정보는 생략할 수 있습니다.
- 그래서 **배열[[행번호]]** 형태로 지정하면 행 조회가 됩니다.

In [13]:
# 3 x 3 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]])
print(a)             

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# 0, 1, 2 행 조회
print(a[[0, 1, 2], :])
print(a[[0, 1, 2]]) # : 생략가능

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# 0, 2 행 조회
print(a[[0, 2]])

[[1 2 3]
 [7 8 9]]


In [18]:
# 0행 조회
print(a[[0]])

[[1 2 3]]


In [22]:
# 0행 조회
print(a[0, :])

[1 2 3]


**특정 열 조회**

- **배열[:,[열번호]]** 형태로 특정 열을 조회합니다.
- 모든 행을 조회하는 경우라 하더라도 **행에 대한 선택 정보를 생략할 수 없습니다.**

In [23]:
# 배열 확인
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
# 0열 조회
print(a[:, [0]])

[[1]
 [4]
 [7]]


In [25]:
# 1열 조회
print(a[:, [1]])

[[2]
 [5]
 [8]]


In [26]:
# 0,1열 조회
print(a[:, [0, 1]])

[[1 2]
 [4 5]
 [7 8]]


**특정 행, 특정 열 조회**

- **배열[[행번호],[열번호]]** 형태로 특정 행의 특정 열을 조회합니다.


In [27]:
# 배열 확인
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
# 0행 0열 조회
print(a[[0], [0]])

[1]


In [29]:
# 1행 1열 조회
print(a[[1], [1]])

[5]


In [30]:
# 2행 1열 조회
print(a[[2], [1]])

[8]


In [31]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
# 0행 0열, 1행 1열 조회
print(a[[0, 1], [0, 1]])

[1 5]


In [33]:
# 0행 0열, 1행 1열, 2행 0열 조회
print(a[[0, 1, 2], [0, 1, 0]])

[1 5 7]


In [34]:
# 0행 1열 두 번 가져옮
print(a[[0, 0], [1, 1]]) 

[2 2]


## 2.2. 기본 슬라이싱

- **배열[행범위,열범위]** 형태로 지정해 그 위치의 요소를 조회합니다.
- 마지막 **범위 값은 대상에 포함되지 않습니다.**
- 즉, **배열[1:m, 2:n]**이라면 1 ~ m-1행, 2 ~ n-1열이 조회 대상이 됩니다.

In [35]:
# 3 x 3 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]])
print(a)             

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
# 0~1행 조회
print(a[0:2])

[[1 2 3]
 [4 5 6]]


In [37]:
# 0~1행, 0~1열 조회
print(a[0:2, 0:2])

[[1 2]
 [4 5]]


In [38]:
# 0~2열, 1~2행 조회
print(a[0:3, 1:3])

[[2 3]
 [5 6]
 [8 9]]


In [39]:
# 1~끝열, 1~끝행 조회
print(a[1:, 1:])

[[5 6]
 [8 9]]


<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align = "left"/>

다음 코드를 실행하여 5x5 배열을 만드시고, 강사가 무작위로 요구하는 요소를 인덱싱 또는 슬라이싱 해보세요.

**[기억할 것] 큰 차원을 따라갑니다**
- 0차원과 0차원이 만나면 0차원
- 0차원과 1차원이 만나면 1차원
- 1차원과 1차원이 만나면 1차원
- 2차원과 1차원이 만나면 2차원
- 2차원과 2차원이 만나면 2차원
- 0차원과 2차원이 만나면 1차원
- 범위는 현재 배열의 차원

In [ ]:
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
print(a)

In [ ]:
# 예 16을 찾으라 하면
print(a[1,0])

## 2.3. 팬시 인덱싱

- 조금 고급스런 인덱싱 방법이 있으며, 이것을 팬시 인덱싱이라 부릅니다.
- **불리안 방식**과 **정수 방식**이 있습니다.

### 2.3.1. 불리안(Boolean) 방식 인덱싱

- 조건을 지정해 그 **조건에 맞는 요소를 선택**하는 방식이 불리안 방식입니다.
- 결과는 1차원이 됩니다.

<img src='https://raw.githubusercontent.com/jangrae/img/master/boolean.png' width=700 align = "left"/>

**1) 1차원 배열**

- 우선 1차원 배열을 만들어 봅니다.

In [40]:
# 1차원 배열 만들기
score = np.array([78, 91, 84, 89, 93, 65])
print(score.shape)
print(score)

(6,)
[78 91 84 89 93 65]


- **score >= 90** 처럼 조회하고자 하는 조건을 먼저 확인합니다.

In [41]:
# 배열의 값이 지정한 조건에 맞는지 여부 확인
print(score >= 90)

[False  True False False  True False]


- **배열[조건]** 형태로 해당 조건에 맞는 요소만 조회합니다.
- **score[score >= 90]**의 경우 90 이상인 요소만 조회하게 됩니다.

In [43]:
# 조건에 맞는 요소 가져오기
print(score[score >= 90])

[91 93]


In [44]:
# 짝수 가져오기
print(score[score % 2 == 0])

[78 84]


<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align = "left"/>

다음 코드를 실행하고 그 의미를 확인해 보세요.

In [45]:
a = [10, 21, 13, 20, 25, 16, 29, 8, 12]
a = np.array(a)
a = list(a[a >= 20])
a

[21, 20, 25, 29]

**2) 2차원 배열**

- 1차원과 같은 방법으로 조회합니다.
- 단 여러 행이 있으므로 행에 대한 조건 조회를 할 수 있습니다.

In [46]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 확인
print(score.shape) 
print(score)

(2, 6)
[[78 91 84 89 93 65]
 [82 87 96 79 91 73]]


**모든 행에 대한 조건**

In [47]:
# 모든 행의 모든 열 값이 90 이상인지 여부
print(score >= 90)

[[False  True False False  True False]
 [False False  True False  True False]]


In [48]:
# 모든 행의 열 값이 90 이상인 값만 가져오기
print(score[score >= 90])

[91 93 96 91]


**특정 행에 대한 조건**

In [49]:
# 0행 확인
print(score[0]) 

[78 91 84 89 93 65]


In [50]:
# 0행의 모든 열 값이 90 이상인지 여부
print(score[0] >= 90)

[False  True False False  True False]


In [51]:
# 0행의 열 값이 90 이상인 값만 가져오기
print(score[0][score[0] >= 90]) 

[91 93]


In [52]:
# 1행 확인
print(score[1])

[82 87 96 79 91 73]


In [53]:
# 1행의 모든 열 값이 90 이상인지 여부
print(score[1] >= 90)

[False False  True False  True False]


In [54]:
# 1행의 열 값이 90 이상인 값만 가져오기
print(score[1][score[1] >= 90])

[96 91]


**복수 조건**

- 여러 조건을 **&** 와 **|** 로 연결하여 조회할 수 있습니다.

In [55]:
# 모든 행의 모든 열 값이 90 이상인지 여부
print((score >= 90) & (score <= 95))

[[False  True False False  True False]
 [False False False False  True False]]


In [56]:
# 모든 행의 열 값이 90 이상인 값만 가져오기
print(score[(score >= 90) & (score <= 95)])

[91 93 91]


<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align = "left"/>

다음 배열에서 짝수만 추출해 보세요.

In [59]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 확인
print(score)

[[78 91 84 89 93 65]
 [82 87 96 79 91 73]]


In [61]:
# 짝수만 추출
print(score % 2 == 0)
print(score[score % 2 == 0])

[[ True False  True False False False]
 [ True False  True False False False]]
[78 84 82 96]


### 2.3.2. 정수 방식 인덱싱

- 정수형 위치 인덱스를 지정해 그 위치의 요소를 조회하는 방식입니다.
- 이미 사용하고 있는 방식이니, 요소 위치를 배열로 선언해 조회하는 방법을 살펴봅니다.

<img src='https://raw.githubusercontent.com/jangrae/img/master/integer.png' width=500 align = "left"/>

In [62]:
# 2차원 배열 만들기
score = np.array([[78, 91, 84, 89],
                  [82, 87, 96, 79],
                  [85, 75, 80, 90],
                  [75, 85, 70, 80]])

# 확인
print(score.shape) 
print(score)

(4, 4)
[[78 91 84 89]
 [82 87 96 79]
 [85 75 80 90]
 [75 85 70 80]]


- 조회할 요소의 위치를 갖는 배열을 만들어 조회할 수 있습니다.
- 특정 위치의 요소를 자주 조회할 경우 그 위치를 배열로 선언해 두면 좋을 것입니다.
- 요소 위치를 꼭 배열로 선언하지 않고 리스트로 선언해도 됩니다.

In [65]:
# 1, 2행 조회
idx1 = np.array([1, 2])
print(idx1)
print(score[idx1])

[1 2]
[[82 87 96 79]
 [85 75 80 90]]


- 위 코드는 다음 코드와 같은 의미를 가집니다.

In [64]:
# 1, 2행 조회
print(score[[1, 2]])

[[82 87 96 79]
 [85 75 80 90]]


- 다음과 같이 열 조회도 가능합니다.

In [66]:
# 1, 2열 조회
idx1 = np.array([1, 2])
print(score[:, idx1])

[[91 84]
 [87 96]
 [75 80]
 [85 70]]


- 위 코드는 다음 코드와 같은 의미를 가집니다.

In [67]:
# 1, 2행 조회
print(score[:, [1, 2]])

[[91 84]
 [87 96]
 [75 80]
 [85 70]]


- 행과 열 위치에 모두 배열을 사용할 수 있습니다.

In [ ]:
# 1, 2행 조회
idx1 = np.array([1, 2])
idx2 = np.array([2, 3])
print(score[idx1, idx2])

In [ ]:
# 1, 2행 조회
idx1 = np.array([1, 2, 3])
idx2 = np.array([1, 2, 3])
print(score[idx1, idx2])

## <center>수고하셨습니다.</center>
<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/end.png' width=200/></center>