<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/title.png' width=500/><center>

<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/practice.png' width=300/></center>

# 실습 목표

- 1, 2, 3차원 배열을 만들 수 있습니다.
- 배열에서 특정 행과 특정 열을 조회할 수 있습니다.
- 배열에서 조건에 맞는 요소를 조회할 수 있습니다.

# P2. [실습] 배열 인덱싱과 슬라이싱

In [0]:
# 라이브러리 불러오기
import numpy as np

1) 다음 형태 갖는 배열을 만들어 **np_arr** 변수로 선언하세요.

In [0]:
# [[  1  2  3]
#  [  4  5  6]
#  [  7  8  9]
#  [ 10 11 12]]

# 배열 만들기
np_arr = np.array([[  1,  2,  3],
                   [  4,  5,  6],
                   [  7,  8,  9],
                   [ 10, 11, 12]])
# 확인
print(np_arr)

2) np_arr의 크기를 확인하세요.

In [0]:
# 배열 크기 확인
print(np_arr.shape)

3) np_arr의 **세 번째** 행의 데이터를 **1차원** 배열로 출력하세요.

In [0]:
# [7 8 9] 조회
print(np_arr[2])

4) np_arr의 **두 번째** 열의 데이터를 **1차원** 배열로 출력하세요.

In [0]:
# [ 2  5  8 11] 조회
print(np_arr[:, 1])

5) np_arr의 **두 번째** 열의 데이터를 **2차원** 배열로 출력하세요.

In [0]:
# 2열 조회
print(np_arr[:, 1:2])

In [0]:
# 배열 확인
np_arr

6) 아래의 출력문이 어떤 값을 출력할 지 추측한 후에 결과를 확인하세요.

In [0]:
# 조건 조회
print(np_arr[np_arr > 7])

7) 위의 실습에서 선택된 요소들의 값을 모두 **2배**로 만드세요.

In [0]:
# 조회 결과에 대한 연산
np_arr[np_arr > 7] = np_arr[np_arr > 7] * 2

8) np_arr을 출력해 보세요.

In [0]:
# 원본 배열 확인
print(np_arr)

9) np_arr의 요소들 중에서 **3의 배수**인 요소만 찾아보세요.(3의 배수 찾는 법: x % 3 == 0)

In [0]:
# 3의 배수 조회
print(np_arr[np_arr % 3 == 0])

## <center>수고하셨습니다.</center>
<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/end.png' width=200/></center>